# Site settings
title: blog do thiago
tag_text: x
description: nothing interesting happened today.
url: "blog.thiagojorge.com"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
