# Site settings
title: it's a blog
tag_text: Good Clean Read
description: false
url: "https://blog.thiagojorge.com"
baseurl: "https://blog.thiagojorge.com"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
